### PR TITLE
Jakedowns merge from upstream 1 31 24

### PR DESCRIPTION
**Pull request by jakedowns**

### CODE REVIEW

**Comment by jakedowns** [comment]
test build apk:

https://drive.google.com/file/d/13lmcD2BI3T_YWrsua6hODZs1QwJCYB7J/view?usp=sharing

**Comment by amwatson** [comment]
Hey, I'm missing context. What is this?

**Comment by amwatson** [comment]
note: I just merged upstream less than two hours ago. Does that include these changes?

**Comment by jakedowns** [comment]
yeah this was basically just me doing the same thing. :bow:

**Pull request closed without merging**
