### PR TITLE
Super Immersive Heuristics

### PR DESCRIPTION
**Pull request by DrBeef**
Implementation of a heuristic scan of registers to find the registers responsible for;

* View Matrix
* Which eye is being drawn

This makes profile #2 of the Super Immersive mode very user friendly (no manual discovery of registers is required)

### CODE REVIEW

**Comment by DrBeef** [comment]
Complete and ready to merge - please let me know if you have any questions. I would even suggest it might be fine to remove the two register settings from the VR options menu since the average user will never use them anyway.

**Comment by amwatson** [comment]
Sorry, didn't notice you put this up! I'll look at it today

**Comment by amwatson** [comment]
Argh, I got caught up in something. So sorry. In the process of looking at it now and it looks good. Will try to pull it in today

**Comment by amwatson** [comment]
Done! Sorry about the wait. Ill aim to be more prompt in the future

**Comment by DrBeef** [comment]
No problem!, thanks for merging it.. I hope people enjoy it when it becomes available.

**Pull request merged**
