### PR TITLE
add screen rotation & resolve right eye black screen issue

### PR DESCRIPTION
**Pull request by sora-blue**
#### Why this PR?
[issue #43 ](https://github.com/amwatson/CitraVR/issues/43)
[issue #44 ](https://github.com/amwatson/CitraVR/issues/44)

#### What does it do?
It adds two entries in settings VR section. 
"vr_rotate_anticlockwise" turns the screen 90 degrees anticlockwise
"vr_render_right_with_left" uses the left eye image to render the right one

#### How has it been tested?
Built and tested on my oculus quest 2, and it works fine. 
Not tested on other devices.

#### Expected Behavior
Before changes
(the right eye sees black screen on top panel)
org citra citra_emu canary debug-20240202-173647

After changes

org citra citra_emu canary debug-20240202-170320

### CODE REVIEW

**Comment by sora-blue** [comment]
Resolved conflicts with upstream/master branch.

**Comment by amwatson** [comment]
I just added a hotkey feature to the latest release (most recent commit). That might be a good option to stick screen rotation behind

**Comment by sora-blue** [comment]
> I just added a hotkey feature to the latest release (most recent commit). That might be a good option to stick screen rotation behind

In citra mainstream project, there's an option called "Rotate Screens Upright" that does the same thing, so maybe it can be put in the settings I suppose.
For hotkeys, I tried to add a new hotkey for screen rotation without messing around too much, but I failed to test it,
since I was faced with the same problem in [issue #4 ](https://github.com/amwatson/CitraVR/issues/4) when trying to bind keys with quest controllers. Maybe an extra gamepad is in need?
btw: Because I cannot test the code for now, changes are put in https://github.com/sora-blue/CitraVR/commit/376544f72f7db97bde4a1615fba1699d540856a4 if you are interested.

**Comment by sora-blue** [comment]
> I just added a hotkey feature to the latest release (most recent commit). That might be a good option to stick screen rotation behind

For interacting directly with quest controllers, how about an alternative aside from hotkeys, like an in-game menu?
Though the UI is not very good at present, and it occupies start button
The result would be like that:
org citra citra_emu canary debug-20240215-175237
Here is the code: https://github.com/sora-blue/CitraVR/commit/275582c659e7177b22e55691eb80bfd50ef33f3b

**Comment by sora-blue** [comment]
Dedided to give it an end, as it's more of a trouble than a help, that anyone else can do these elementary changes. I'd lost interest in it, and no one else was interested in it. Thanks for maintainers' amazing work that makes it possible to play 3ds on quest anyway.

**Pull request closed without merging**
